"""npcs

Revision ID: 85f4fc660cd6
Revises: 9220fb4518f3
Create Date: 2026-05-23 22:55:14.472825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85f4fc660cd6'
down_revision: Union[str, None] = '9220fb4518f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_name'), 'npcs', ['name'], unique=True)
    op.create_table('adventure_npcs',
    sa.Column('adventure_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adventure_id', 'npc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adventure_npcs')
    op.drop_index(op.f('ix_npcs_name'), table_name='npcs')
    op.drop_table('npcs')
    # ### end Alembic commands ###
